CREATE TABLE sms_notification (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    event_key VARCHAR(160) NOT NULL COMMENT '同一业务事件和收件人的幂等键',
    event_type VARCHAR(64) NOT NULL COMMENT 'INSTALLER_ASSIGNED/DEALER_APPOINTMENT_CREATED 等',
    business_type VARCHAR(64) NOT NULL COMMENT 'WORK_ORDER/DEALER_APPOINTMENT 等',
    business_id VARCHAR(64) NOT NULL COMMENT '业务主键',
    recipient_phone VARCHAR(20) NOT NULL COMMENT '收件人手机号，仅后端审计使用',
    template_code VARCHAR(128) NULL COMMENT '阿里云短信模板 Code',
    template_params_json JSON NULL COMMENT '模板参数，不保存凭据',
    notification_status VARCHAR(32) NOT NULL COMMENT 'PENDING/SENDING/SENT/FAILED/SKIPPED',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已发起的调用次数',
    last_attempt_at DATETIME(3) NULL,
    next_attempt_at DATETIME(3) NULL,
    sent_at DATETIME(3) NULL,
    provider_request_id VARCHAR(128) NULL COMMENT '阿里云 RequestId',
    provider_biz_id VARCHAR(128) NULL COMMENT '阿里云 BizId',
    provider_code VARCHAR(64) NULL COMMENT '阿里云业务代码',
    last_error VARCHAR(1000) NULL COMMENT '脱敏后的失败原因',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_sms_notification_event (event_key),
    KEY idx_sms_notification_retry (notification_status, next_attempt_at, attempt_count),
    KEY idx_sms_notification_business (business_type, business_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='短信通知投递记录';
