<template>
	<view class="page"><view v-if="loading" class="state"><up-loading-icon color="#0b63ce"></up-loading-icon><text>正在加载订单详情</text></view><view v-else-if="error" class="state"><text>{{ error }}</text><view class="outline-button" @click="loadDetail">重新加载</view></view><template v-else>
		<view class="summary"><view class="summary-head"><view><text class="title">{{ detail.orderName }}</text><text class="order-no">{{ detail.orderNo }}</text></view><text class="status">已下单</text></view><view class="summary-row"><text>下单时间</text><text>{{ formatTime(detail.createdAt) }}</text></view><view v-if="detail.pickupPhone" class="summary-row"><text>取货联系电话</text><text class="phone" @click="callPickup">{{ detail.pickupPhone }}</text></view></view>
		<view class="items-card"><text class="section-title">耗材明细</text><view v-for="item in detail.items" :key="item.id" class="item"><view><text class="item-name">{{ item.productName }}</text><text class="item-spec">{{ item.specLabel || '通用规格' }}</text><text class="sku-code">SKU：{{ item.skuCode }}</text></view><text class="quantity">× {{ item.quantity }} {{ item.unit }}</text></view></view>
		<view class="notice"><up-icon name="info-circle" size="18" color="#0b63ce"></up-icon><text>本单仅作为取货记录，不包含价格、支付，也不会自动扣减库存或自动出库。</text></view>
	</template></view>
</template>
<script setup>
import { ref } from 'vue';import { onLoad } from '@dcloudio/uni-app';import { installerMaterialApi } from '@/api/api.js';import { formatDateTime } from '@/utils/time.js'
const id=ref(''),detail=ref({items:[]}),loading=ref(true),error=ref('');const loadDetail=async()=>{loading.value=true;error.value='';try{const res=await installerMaterialApi.getOrderDetail(id.value);if(res.code===200)detail.value=res.data||{items:[]};else error.value=res.msg||'订单加载失败'}catch{error.value='网络异常，请稍后重试'}finally{loading.value=false}};onLoad(options=>{id.value=options?.id||'';loadDetail()});const formatTime=value=>formatDateTime(value);const callPickup=()=>detail.value.pickupPhone&&uni.makePhoneCall({phoneNumber:detail.value.pickupPhone.replace(/[^\d]/g,'')})
</script>
<style scoped lang="scss">
.page{min-height:100vh;padding:24rpx;box-sizing:border-box;background:#f4f7fb}.state{min-height:560rpx;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18rpx;color:#8b9aaa;font-size:24rpx}.outline-button{height:70rpx;padding:0 32rpx;border:2rpx solid #0b63ce;border-radius:18rpx;display:flex;align-items:center;color:#0b63ce}.summary,.items-card{padding:30rpx;border-radius:22rpx;background:#fff;box-shadow:0 4rpx 16rpx rgba(30,41,59,.05)}.summary-head,.summary-row,.item{display:flex;align-items:center;justify-content:space-between}.title{display:block;color:#142434;font-size:32rpx;font-weight:750}.order-no{display:block;margin-top:8rpx;color:#64748b;font-size:23rpx}.status{padding:8rpx 17rpx;border-radius:18rpx;background:#eaf3ff;color:#0b63ce;font-size:22rpx}.summary-row{margin-top:24rpx;padding-top:20rpx;border-top:1rpx solid #edf1f5;color:#64748b;font-size:23rpx}.summary-row text:last-child{color:#142434}.summary-row .phone{color:#0b63ce}.items-card{margin-top:20rpx}.section-title{display:block;margin-bottom:8rpx;color:#142434;font-size:29rpx;font-weight:700}.item{padding:24rpx 0;border-bottom:1rpx solid #edf1f5}.item:last-child{border-bottom:0}.item-name{display:block;color:#142434;font-size:27rpx;font-weight:650}.item-spec{display:block;margin-top:8rpx;color:#475569;font-size:23rpx}.sku-code{display:block;margin-top:6rpx;color:#94a3b8;font-size:20rpx}.quantity{color:#0b63ce;font-size:25rpx;font-weight:650}.notice{display:flex;align-items:flex-start;gap:12rpx;margin-top:20rpx;padding:22rpx;border-radius:18rpx;background:#eaf3ff;color:#52677d;font-size:22rpx;line-height:1.6}
</style>
